### ISSUE TITLE
8 x 6A?

### ISSUE THREAD

**Issue by baennjer** [ronnythomas/HM-MOD-Re-8#1]
8 x 6A finde ich irreführend.
L1 ist über eine 6,3A Sicherung geführt.
In Summe 48 mögliche Amperes wären wohl auch für die Leiterbahn etwas viel...

Ich würde das Layout so ändern dass es 8 potenzialfreie Kontakte sind.
Noch besser wäre es mit den 230V von der Platine weg zu bleiben und dafür Koppelrelais auf Hutschiene zu verwenden.

Trotzdem cooles Umsetzung mit top Platine

**Comment by ronnythomas** [comment]
Danke für den Hinweis. Für die Hutschiene gibt es ein anderes Gerät
